# 1

Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [85]:
#MELEK İNCİ        
import numpy as np

sayilar=np.array([0.1,2.54,4.57,6.43,8,10.01], dtype="int")
print(sayilar)
print(sayilar.ndim)
print(sayilar.size)

[ 0  2  4  6  8 10]
1
6


# 2
İki ve üç boyutlu arrayler oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım. 

Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapalım.

In [86]:
dizi1=np.array([[0,2,4,6],[61,17,34,36]])
dizi2=np.array([[[13,2,2001,25],[0,4,3,4],[6,9,3,0]]])
print(dizi1.ndim)
print(dizi1.size)
print(dizi2.ndim)
print(dizi2.size)

dizi1[1]

2
8
3
12


array([61, 17, 34, 36])

In [87]:
dizi2[0,1]

array([0, 4, 3, 4])

In [88]:
dizi1[:2]

array([[ 0,  2,  4,  6],
       [61, 17, 34, 36]])

In [89]:
dizi2[0:,1,3]

array([4])

# 3

Numpy fonksiyonu kullanarak bir, iki ve üç boyutlu arrayler oluşturalım. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapalım.

In [90]:
array1=np.array([11,22,33,44,55,66,77,88,99])


array2=np.array([[1,2,3,4,5,6,7],
                 [9,8,7,6,5,4,3]])


array3=np.array([[[1,3,3,4,5,0,3,2,1],
                 [33,22,11,44,55,66,77,88,99],  
                 [4,34,52,71,25,1,43,15,63]],
                  
                [[1,2,3,4,5,6,7,8,9],
                 [1,1,4,41,21,62,91,80,17],  
                 [0,1,2,3,4,6,7,8,5]]])


In [91]:
array1[6]

77

In [92]:
array1[1:3]

array([22, 33])

In [93]:
array1[:8]

array([11, 22, 33, 44, 55, 66, 77, 88])

In [94]:
array2[0,6]

7

In [95]:
array2[1,5]

4

In [96]:
array2[:1]

array([[1, 2, 3, 4, 5, 6, 7]])

In [97]:
array3[1,1,2]

4

In [98]:
array3[0:,2,1]

array([34,  1])

In [99]:
array3[0:,1:,4]

array([[55, 25],
       [21,  4]])

# 4

Sıfırlardan oluşan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [100]:
zeros_array = np.zeros((3, 3),dtype="int")
ones_array = np.ones((3, 3),dtype="int") 

In [101]:
print(zeros_array)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [102]:
print(ones_array)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [103]:
np.concatenate((zeros_array, ones_array), axis=0) 

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [104]:
np.concatenate((zeros_array, ones_array), axis=1) 

array([[0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1]])